feat: add CI/CD blueprint
camunda/camunda-platform-tutorials pull request #59
Opened 2024-04-15 12:51 UTC by wollefitz

Part of https://github.com/camunda/web-modeler/issues/8961

2024-04-15 19:05 UTC, wollefitz commented
@HanselIdes Could you have a look at the readme if it is easy to understand and additionally the process itself? 

A couple of things to take into account:
* At the moment, it is using collapsed subprocesses so it's not compatible with Zeebe < 8.4 - I can change this if we want to target these cluster versions.
* Under which name to we want to offer this process? I went with "CI/CD Pipeline" for now as you mentioned that "PDLC" is not what users might be used to

2024-04-16 07:52 UTC, HanselIdes approved these changes
@wollefitz I'm looking forward to sharing this template with our GitLab-using customers. I added a few non-blocking comments
In addition, there should be a docs PR that advertises this (ideally with an animated visual showing the user experience)

2024-04-16 07:52 UTC, HanselIdes commented on solutions/ci-cd/README.md
> +1. In [Console](https://console.cloud.camunda.io), navigate to the "Organization" > "Administration API".
FYI: My first thought when reading this is the cost of maintenance. If you can link to docs page, you will not have to maintain it (although the user experience might not be so good)

I don't have a recommendation on which path to follow though

2024-04-16 07:52 UTC, HanselIdes commented on solutions/ci-cd/README.md
> +After starting a process instance, it will create a pull request with the contents of the target folder in the target repository.
If this isn't a dropdown, then the user should get instructions on how to find the folder ID

2024-04-16 07:52 UTC, HanselIdes commented on solutions/ci-cd/README.md
> +* Concurrent runs of the blueprint are not supported. This means that if you start the blueprint while another instance is still running, deployment information might be mixed between the two instanc
We should be very clear that this is fully customizable, so this is a good place to discuss other limitations you've run into
For example, it's a great place to mention GitHub's limitations around base64 encoding

2024-04-16 08:58 UTC, HanselIdes requested changes
I also answered your questions and reviewed the BPMN diagram.
The main thing I'd like to see changed is the addition of documentation. With the new design, it should be a more effective way of explaining the key concepts in case the user wants to modify the process

2024-04-16 08:58 UTC, HanselIdes commented on solutions/ci-cd/README.md
> +
```suggestion

Camunda can also be used to orchestrate your process development lifecycle (PDLC), covering all steps from change reviews to release activities.
```

2024-04-16 08:58 UTC, HanselIdes commented on solutions/ci-cd/README.md
> +This blueprint demonstrates a CI/CD pipeline for deploying a file to different environments using GitLab and Camunda Platform 8.
```suggestion
This blueprint demonstrates a customizable CI/CD pipeline for deploying a file to different environments using GitLab and Camunda Platform 8.
```

2024-04-16 08:58 UTC, HanselIdes commented on solutions/ci-cd/CI-CD Pipeline.bpmn
> +      "id": "Field_1ng3kqk",
Readable IDs would be nice to have, especially when they might appear in error messages

2024-04-16 08:58 UTC, HanselIdes commented on solutions/ci-cd/CI-CD Pipeline.bpmn
> +}</zeebe:userTaskForm>
I recommend adding Documentation as the primary way that a user understands "what is this and how does it work?" instead of just relying on the readme

2024-04-17 13:48 UTC, wollefitz commented on solutions/ci-cd/README.md
> +1. In [Console](https://console.cloud.camunda.io), navigate to the "Organization" > "Administration API".
Let's link to the documentation page, it's also already linked in the Self-Managed section.

2024-04-17 14:15 UTC, wollefitz commented on solutions/ci-cd/README.md
> +After starting a process instance, it will create a pull request with the contents of the target folder in the target repository.
Added some information plus a screenshot

2024-04-17 20:13 UTC, wollefitz commented on solutions/ci-cd/CI-CD Pipeline.bpmn
> +}</zeebe:userTaskForm>
@HanselIdes I added a short introduction to both forms to clarify the usage of the blueprint. Do you think that's enough or do you think "in-diagram" documentation should be more verbose in general?

2024-04-17 20:27 UTC, wollefitz commented on solutions/ci-cd/CI-CD Pipeline.bpmn
> +}</zeebe:userTaskForm>
Great point! Added this limitation and another sentence to the introduction: "The blueprint is designed to be used with GitLab, but can be adapted to work with other CI/CD tools."

2024-04-17 20:27 UTC, wollefitz commented on solutions/ci-cd/README.md
> +* Concurrent runs of the blueprint are not supported. This means that if you start the blueprint while another instance is still running, deployment information might be mixed between the two instanc
Great point! Added this limitation and another sentence to the introduction: "The blueprint is designed to be used with GitLab, but can be adapted to work with other CI/CD tools."

2024-04-17 20:29 UTC, wollefitz commented
FYI: @HanselIdes Till was so kind to review the blueprint in a separate PR (see https://github.com/camunda/camunda-platform-tutorials/pull/61) which is merged to this branch now. Could you have another look at the changes?

2024-04-19 11:59 UTC, HanselIdes approved these changes
I contributed some process documentation and recommended some grammar and spelling changes. You don't need to re-request my review.

2024-04-19 11:59 UTC, HanselIdes commented on solutions/ci-cd/README.md
> +2Camunda can also be used to orchestrate your process development lifecycle (PDLC), covering all steps from change reviews to release activities.. Click on "Create" and create a connector secret `WEB
```suggestion
2. Camunda can also be used to orchestrate your process development lifecycle (PDLC), covering all steps from change reviews to release activities.. Click on "Create" and create a connector secret `WEB_MODELER_CLIENT_ID` and `WEB_MODELER_CLIENT_SECRET` in the cluster you want to use the blueprint in and set the values to the "Client ID" and "Client Secret" respectively.
```

2024-04-19 11:59 UTC, HanselIdes commented on solutions/ci-cd/README.md
> +To check the status of the process, you can always use [Camunda Operate](https://docs.camunda.io/docs/next/components/operate/operate-introduction/) to have a look at the status of the process.
```suggestion
To check the status of the process, you can always use [Camunda Operate](https://docs.camunda.io/docs/next/components/operate/operate-introduction/) to track the status of the process.
```

2024-04-19 11:59 UTC, HanselIdes commented on solutions/ci-cd/README.md
> +Operate should indicate with blue colored sequence flows the where to process went and mark the current activity with a green circle:
```suggestion
Operate should indicate with blue colored sequence flows where the process went and mark the current activity with a green circle:
```

2024-04-19 11:59 UTC, HanselIdes commented on solutions/ci-cd/README.md
> +This blueprint demonstrates a customizable CI/CD pipeline for deploying a file to different environments using GitLab and Camunda Platform 8.
```suggestion
This blueprint demonstrates a customizable CI/CD pipeline for deploying a file to different environments using GitLab and Camunda Platform 8. To learn more about the topic, review [Integrate Web Modeler into CI/CD](https://docs.camunda.io/docs/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd/)
```

2024-04-19 12:00 UTC, HanselIdes commented on solutions/ci-cd/CI-CD Pipeline.bpmn
> +}</zeebe:userTaskForm>
I think the in-diagram documentation should be more verbose and explain what's happening in plain English. I shared some examples to the top level of process.

2024-04-20 10:50 UTC, merged